name: SudoSigns-OG
version: '${version}' 
author: MylesMor
main: dev.mylesmor.sudosigns.SudoSigns
softdepend: [Multiverse-Core, Vault]
api-version: '${apiVersion}'
commands:
  sudosigns:
    description: Opens the SudoSigns help menu.
    aliases: [sudosign, ss]
